// Generates src/assets/help/help-content.json from the documents in user-docs/, for the Help menu.
//
// The point of doing this at build time rather than reading the files when the menu is used is
// that a release should show the documentation as it stood when that release was built. The files
// in the repository move on; a copy of the app should not silently follow them. Running from source
// behaves the same way for the same reason: editing a document changes nothing in the app until
// this script is run, which is a deliberate step, not a side effect of starting up.
//
// So it is committed output, exactly like the chord library, and built with:
//   npm run build:help
//
// README.md is not used. It is about the repository, not about using unstrung.

import * as fs from 'node:fs';
import * as path from 'node:path';
import { markdownBodyToHtml } from '../src/shared/markdown.mjs';
import { HELP_DOCUMENTS, ABOUT_DOCUMENT, documentTitle } from './help-documents.mjs';

const USER_DOCS = path.join(import.meta.dirname, '..', 'user-docs');
const OUT_PATH = path.join(import.meta.dirname, '..', 'src', 'assets', 'help', 'help-content.json');

// A link may be written relative to eyesunstrung.vip, such as [Introduction](/unstrung/docs/introduction/),
// as on the site's own pages. The app has no site to resolve that against, so it is made a full
// address here, before anything else reads the text: markdown.mjs links only full addresses, and
// the list of links the app may open is collected from these. The site reads the files as they
// are, where a relative link is already right.
const SITE = 'https://eyesunstrung.vip';
const read = name => fs.readFileSync(path.join(USER_DOCS, `${name}.md`), 'utf8')
    .replace(/\]\((\/[^)\s]*)\)/g, (_match, sitePath) => `](${SITE}${sitePath})`);

// Each document opens as an item in the list of open items. The item's own h1 is the document's
// title, and renderer.js repeats it as an h1 at the start of the document in the main area, so the
// body starts at h2 beneath both. The About dialog is titled with an h1 too.
const documents = HELP_DOCUMENTS.map(({ id }) => {
    const markdown = read(id);
    return { id, title: documentTitle(markdown, id), html: markdownBodyToHtml(markdown, { startLevel: 2 }) };
});
const aboutMarkdown = read(ABOUT_DOCUMENT);
const aboutHtml = markdownBodyToHtml(aboutMarkdown, { startLevel: 2 });

// The links these documents offer, so the main process can allow exactly those through to the
// browser. Collected here because the markdown is only read here: at runtime there is nothing left
// to scan.
const allMarkdown = [...HELP_DOCUMENTS.map(({ id }) => read(id)), aboutMarkdown].join('\n');
const urls = [...new Set(
    [...allMarkdown.matchAll(/\]\((https?:\/\/[^)\s]+)\)/g)].map(match => match[1])
)].sort();

// No build date. This file is committed, and a timestamp would make it differ from its own
// regenerated output every day, which both creates pointless diffs and makes a staleness check
// meaningless. Everything here is a function of user-docs alone; git records when it changed.
const content = {
    source: 'user-docs/',
    note: 'Generated by scripts/build-help.mjs. Run npm run build:help after editing anything in user-docs.',
    documents,
    aboutHtml,
    urls
};

fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
fs.writeFileSync(OUT_PATH, JSON.stringify(content, null, 2), 'utf8');

// --- Report ---------------------------------------------------------------------------
console.log('=== help content build ===');
console.log(`output:   ${path.relative(process.cwd(), OUT_PATH)} ` +
    `(${(fs.statSync(OUT_PATH).size / 1024).toFixed(0)} KB)`);
for (const { id, title, html } of [...documents, { id: ABOUT_DOCUMENT, title: 'About dialog', html: aboutHtml }]) {
    console.log(`\n${id}: "${title}", ${(html.match(/<h\d>/g) ?? []).length} headings, ` +
        `${(html.match(/<p>/g) ?? []).length} paragraphs, ${(html.match(/<a /g) ?? []).length} links`);
}
console.log(`\nlinks allowed through to the browser (${urls.length}):`);
for (const url of urls) console.log(`  ${url}`);
