// Generates src/assets/help/help-content.json from README.md, for the Help menu documents.
//
// The point of doing this at build time rather than reading README.md when the dialog opens is that
// a release should show the README as it stood when that release was built. The file in the
// repository moves on; a copy of the app should not silently follow it. Running from source behaves
// the same way for the same reason: editing README.md changes nothing in the app until this script
// is run, which is a deliberate step, not a side effect of starting up.
//
// So it is committed output, exactly like the chord library, and built with:
//   npm run build:help

import * as fs from 'node:fs';
import * as path from 'node:path';
import { markdownBodyToHtml, markdownSection } from '../src/shared/markdown.mjs';

const README_PATH = path.join(import.meta.dirname, '..', 'README.md');
const OUT_PATH = path.join(import.meta.dirname, '..', 'src', 'assets', 'help', 'help-content.json');

// Sections lifted out for their own Help menu entries, keyed by the field they land in.
const SECTIONS = {
    screenReaderHtml: 'Screen Reader Users',
    feedbackHtml: 'Feedback'
};

const markdown = fs.readFileSync(README_PATH, 'utf8');

// Every document is shown in a dialog titled with an h2, so their own sections start at h3.
const whatIsHtml = markdownBodyToHtml(markdown, { startLevel: 3 });

const sections = {};
for (const [field, heading] of Object.entries(SECTIONS)) {
    const source = markdownSection(markdown, heading);
    if (source === null) {
        throw new Error(`README.md has no "${heading}" section, which the Help menu needs`);
    }
    sections[field] = markdownBodyToHtml(source, { startLevel: 3 });
}

// The links these documents offer, so the main process can allow exactly those through to the
// browser. Collected here because the markdown is only read here: at runtime there is nothing left
// to scan.
const urls = [...new Set(
    [...markdown.matchAll(/\]\((https?:\/\/[^)\s]+)\)/g)].map(match => match[1])
)].sort();

const content = {
    generated: new Date().toISOString().slice(0, 10),
    source: 'README.md',
    note: 'Generated by scripts/build-help.mjs. Run npm run build:help after editing README.md.',
    whatIsHtml,
    ...sections,
    urls
};

fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
fs.writeFileSync(OUT_PATH, JSON.stringify(content, null, 2), 'utf8');

// --- Report ---------------------------------------------------------------------------
const headings = [...whatIsHtml.matchAll(/<(h\d)>(.*?)<\/\1>/g)];
console.log('=== help content build ===');
console.log(`source:   ${path.relative(process.cwd(), README_PATH)}`);
console.log(`output:   ${path.relative(process.cwd(), OUT_PATH)} ` +
    `(${(fs.statSync(OUT_PATH).size / 1024).toFixed(0)} KB)`);
console.log(`\nWhat is Unstrung: ${headings.length} headings, ` +
    `${(whatIsHtml.match(/<p>/g) ?? []).length} paragraphs, ` +
    `${(whatIsHtml.match(/<a /g) ?? []).length} links`);
for (const [, tag, text] of headings) console.log(`  ${tag}: ${text.replace(/<[^>]+>/g, '')}`);
for (const [field, heading] of Object.entries(SECTIONS)) {
    const html = sections[field];
    console.log(`\n${heading}: ${(html.match(/<p>/g) ?? []).length} paragraphs, ` +
        `${(html.match(/<h\d>/g) ?? []).length} headings, ` +
        `${(html.match(/<a /g) ?? []).length} links`);
}
console.log(`\nlinks allowed through to the browser (${urls.length}):`);
for (const url of urls) console.log(`  ${url}`);
